# Generated by Django 5.0.7 on 2024-07-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_myrentsmodel_rent_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentmodel',
            old_name='free_place_count',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='apartmentmodel',
            old_name='price',
            new_name='price_per_night',
        ),
    ]
