# Generated by Django 5.0.7 on 2024-07-22 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_rename_free_place_count_apartmentmodel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrentsmodel',
            name='aparments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apartment.apartmentmodel'),
        ),
    ]
